==========================================================
  Introduction to NO-SQL
=========================================================
NoSQL->Not only SQL
(SQL is not the only language for database problems)(other language exist)

NoSQL
* Types of Database Management System
* new technology


History
* early mid 1980s ->rise of RDBMS

Benifits of RDBMS
* data persistence(DATA consistency)
* SQL(common for all RDBMS)(all RDBMS can communicate with each other)
* support for complex TRANSACTION
* Reporting tools available(e.g. oracle reports,oracle graphics,
  actuate,crystal reports, etc)
* Integration mechanism between applications 

----------------------------------------------------------------------------------
Problems with RDBMS model:
----------------------------------------------------------------------------------

Impedance mismatch-> one logical unit in the memory, when saved is splattered across
multiple table in the database.

Solution:-
* mid 1990s rise of object database
  e.g. oracle(RDBMS+OODBMS)-> ORDBMS
  offerings:
   Abtsract datatypes(user defined),Nested Abstract datatypes, 
   object views, Instead of triggers, Collections,varrays,varrays basesd on 
   abstract datatype,nested tables,user method,table partititoning, index parrtitioning,
   bitman indexes,index oragnized etc
   
 High traffic Websites
 
 Google-->>Bigtable (Columnar database)(every column is a file)
 Amazon-->>Dynamo  (columnar database) (Every columns)
 
 Birth of NoSQL
 
 Twitte Hastag to publicize the meeting:-
 san francisco,thu 11th jan,2009 from 10 am to 5pm
 
 #noSQL
 
 comapanies who attented:-
 MongoDB
 CouchDB(relax)
 Project voldemort
 cassabdra(eye of beautiful women)
 Dynomite
 Apache HBASE
 
 Defination of NoSQL-
 * no defination of NoSQL
 Characteristics of NoSQL-
 1. Non relationals(no relationship between elements)
 2. Open source
 3. Cluster friendly(ability run acress clusters)(scaling horizeontally)
 4. Designed for the 21st Century web(High traffic websites)
 5. schema-LESS
 
 